file_to_update: "20.1.1-to-20.1.2.tar.gz.enc"
remote_builds_directory: "/var/www/abshar/bin/builds"
local_target_directory: "/var/www/html/baadbaan-docker/baadbaan_new/storage/app/patches"
log_file_path: "/var/www/html/services/update-toolbox/app.log"
