- name: Check the log file
  ansible.builtin.command: cat /var/www/html/services/update-toolbox/app.log
  register: log_content
  until: log_content.stdout.endswith('Completed Update')
  retries: 5
  delay: 10
  register: remaining_retries
  notify: Show remaining retries

- name: Fail if the update was not successful
  ansible.builtin.fail:
    msg: "Update did not complete successfully"
  when: not log_content.stdout.endswith('Completed Update')

- name: Success message
  ansible.builtin.debug:
    msg: "Update completed successfully"
  when: log_content.stdout.endswith('Completed Update')
  notify: Show remaining retries
