- name: Fetch the update file from the remote server
  include_tasks: fetch_update_file.yml

- name: Transfer the update file to the target server
  include_tasks: transfer_update_file.yml

- name: Apply the update using curl
  include_tasks: apply_update.yml

- name: Verify the update process
  include_tasks: verify_update.yml
