- name: Copy the verify_update.sh script to the remote server
  ansible.builtin.copy:
    src: /tmp/ansible-app-updater/verify_update.sh
    dest: /tmp/verify_update.sh
    mode: '0755'

- name: Execute the verify_update.sh script
  ansible.builtin.shell: /tmp/verify_update.sh
  register: verify_update_result
  ignore_errors: yes

- name: Fail if the update did not complete successfully
  ansible.builtin.fail:
    msg: "Update did not complete successfully. Check the log for details."
  when: verify_update_result.rc != 0

- name: Display success message
  ansible.builtin.debug:
    msg: "Update completed successfully."
  when: verify_update_result.rc == 0
